### ISSUE TITLE
Translating README to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [toddmotto/angularjs-styleguide#171]
HI! I would like to contribute with this project by offering a translation in to Spanish (my native language) I can translate any PR you want. I work for Utopian-io as translator. Let me know if interested!

**Comment by TorzuoliH** [comment]
Hi @LuigiBaute!

This styleguide is already translated - or partially, i don't know - in Spanish language here: https://github.com/toddmotto/angularjs-styleguide/blob/master/i18n/es.md

**Comment by LuigiBaute** [comment]
I see. didn't notice that, do you have any PR that you with to be translated? I'm available! :+1: Cheers!

**Comment by TorzuoliH** [comment]
Up to you to check if Spanish translation has been done partially or fully :-)

**Comment by nbpalomino** [comment]
Hey guys, check this. #177 

Spanish translation doesn't match with current version...
