### ISSUE TITLE
question about the way to unbind multiple listeners on $destroy

### ISSUE THREAD

**Issue by RoyLING** [toddmotto/angularjs-styleguide#35]
In [event pub/sub section](https://github.com/toddmotto/angularjs-styleguide#publish-and-subscribe-events), why do we unbind listener within multiple $destroy event binding?
>```js
var rootListeners = {
  'customEvent1': $rootScope.$on('customEvent1'[, callback]),
  'customEvent2': $rootScope.$on('customEvent2'[, callback]),
  'customEvent3': $rootScope.$on('customEvent3'[, callback])
};
for (var unbind in rootListeners) {
  $scope.$on('$destroy', rootListeners[unbind]);
}
```

Can we do this instead? move for loop into the $destroy event handler
```js
$scope.$on('$destroy', function() {
  for (var unbind in rootListeners) {
    rootListeners[unbind]();
  }
});
```

**Comment by Stephn-R** [comment]
I like this idea better. The original looks like I am attaching unique handlers to each rootListener. Why not just one catch all?

**Comment by toddmotto** [comment]
Just updated it, I've been using an Array instead of Object lately, so added this syntax:

```js
    var unbind = [
      $rootScope.$on('customEvent1'[, callback]),
      $rootScope.$on('customEvent2'[, callback]),
      $rootScope.$on('customEvent3'[, callback])
    ];
    $scope.$on('$destroy', function () {
      unbind.forEach(function (fn) {
        fn();
      });
    });
```
