### ISSUE TITLE
Controllers#Inheritance : what about BaseCtrl in the global namespace ???

### ISSUE THREAD

**Issue by fabm22** [toddmotto/angularjs-styleguide#37]
The rule for inheritance seems to advocate to put ours base Controllers (the 'parent' controllers) in the global namespace ... since we cant use injector to get a reference to the base controller where we would want it ( in IIFE definition of another (child) Controller )...or am I missing something ?

Thanks a lot

**Comment by arg20** [comment]
+1 On this question

**Comment by toddmotto** [comment]
@fabm22 @arg20 Hey all, so the "IIFE scoping" section of this guide suggests using an IIFE to wrap the module / concatenated files at build time - thus the Controller would be available in the same JavaScript scope, but be "shielded" from being global.
